const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const assert = (value, message) => { if (!value) throw new Error(message); };
const manifest = JSON.parse(read('manifest.json'));
const panel = read('sidepanel.html');
const panelJs = read('sidepanel.js');
const worker = read('service_worker.js');
const content = read('content.js');
const offscreen = read('offscreen.js');
assert(manifest.name.includes('Beta 16'), 'manifest Beta 16');
assert(content.includes("0.7.9-beta.16"), 'content version');
assert(worker.includes("0.7.9-beta.16"), 'worker version');
assert(offscreen.includes('0.7.9-beta.16'), 'offscreen version');
assert(panel.includes('Integrated Beta 16'), 'panel version');
assert(!panel.includes('structural-approval'), 'approval UI removed');
assert(!panelJs.includes('runApproveStructural'), 'approval handler removed');
assert(worker.includes('structuralOperationIdsFromPatch'), 'auto structural approval present');
assert(worker.includes("confirmation_mode = 'single_apply_click_after_dry_run'"), 'single confirm mode');
assert(worker.includes('SubmitTempItemAnswer'), 'save verification preserved');
assert(worker.includes('rollback'), 'rollback preserved');
console.log('beta16_static.test.js PASS');
