'use strict';

const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const assert = (value, message) => { if (!value) throw new Error(message); };
const manifest = JSON.parse(read('manifest.json'));
const panel = read('sidepanel.html');
const worker = read('service_worker.js');
const content = read('content.js');
const offscreen = read('offscreen.js');
const recovery = read('recovery_engine.js');

assert(manifest.name.includes('Beta 17'), 'manifest Beta 17');
assert(content.includes("0.7.9-beta.17"), 'content version');
assert(worker.includes("0.7.9-beta.17"), 'worker version');
assert(offscreen.includes('0.7.9-beta.17'), 'offscreen version');
assert(panel.includes('Integrated Beta 17'), 'panel version');
assert(worker.includes("importScripts('patch_engine.js', 'recovery_engine.js')"), 'recovery engine imported');
assert(recovery.includes('classifyStep'), 'recovery classifier exists');
assert(worker.includes('AIDPRecoveryEngine.classifyStep'), 'structural rollback uses partial-state classifier');
assert(worker.includes("item.status = 'failed'"), 'failed operation persisted');
assert(worker.includes('operationError?.adapter_result'), 'adapter_result persisted on operation error');
assert(worker.includes("split_region: false"), 'normal split disabled pending native ID generator proof');
assert(worker.includes("add_region: false"), 'normal add disabled pending native ID generator proof');
assert(worker.includes("delete_region: false"), 'normal delete disabled pending structural verification');
assert(panel.includes('既存journalの安全復元にだけ使用'), 'UI explains structural safety gate');
assert(!worker.includes('PointerEvent('), 'service worker does not use synthetic pointer events');
assert(!worker.includes('MouseEvent('), 'service worker does not use synthetic mouse events');
assert(!worker.includes('chrome.tabs.reload('), 'extension does not auto reload AIDP');
console.log('beta17_static.test.js: PASS');
